from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.config import ALLOWED_SYMBOL


DEFAULT_SUMMARY_PATH = Path("logs/strategy_param_sweep_summary.json")
DEFAULT_OUTPUT_PATH = Path(".env.candidate")
SAFETY_ENV = {
    "PAPER_TRADING_ONLY": True,
    "SYMBOL": ALLOWED_SYMBOL,
    "TRADING_ENABLED": False,
    "AUTO_TRADE_ENABLED": False,
    "ALLOW_FALLBACK_TRADING": False,
    "SCALPING_MODE_ENABLED": True,
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write a selected strategy sweep parameter set to .env.candidate only."
    )
    parser.add_argument("--parameter-set-id", required=True, help="Exact parameter_set_id from strategy_param_sweep_summary.json")
    parser.add_argument("--summary-path", default=str(DEFAULT_SUMMARY_PATH), help="Path to sweep summary JSON")
    parser.add_argument("--output-path", default=str(DEFAULT_OUTPUT_PATH), help="Output path; defaults to .env.candidate")
    args = parser.parse_args()

    result = write_candidate_config(
        parameter_set_id=args.parameter_set_id,
        summary_path=Path(args.summary_path),
        output_path=Path(args.output_path),
        current_env_path=Path(".env"),
    )
    print(result["diff_summary"])
    print("")
    print(f"wrote: {result['output_path']}")
    print("WARNING: Backtests do not guarantee future results. Run this only as paper-forward evaluation.")
    print("This script never modifies .env and does not enable live trading.")


def write_candidate_config(
    *,
    parameter_set_id: str,
    summary_path: Path = DEFAULT_SUMMARY_PATH,
    output_path: Path = DEFAULT_OUTPUT_PATH,
    current_env_path: Path = Path(".env"),
) -> dict[str, Any]:
    if output_path.name == ".env" or output_path.resolve() == current_env_path.resolve():
        raise ValueError("Refusing to write production .env. Use .env.candidate.")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    candidate = candidate_config_from_summary(summary, parameter_set_id)
    env_values = {
        **candidate["env_overrides"],
        **SAFETY_ENV,
    }
    ordered_values = _ordered_env_values(env_values)
    output_path.write_text(_format_candidate_env(parameter_set_id, ordered_values), encoding="utf-8")
    return {
        "parameter_set_id": parameter_set_id,
        "output_path": str(output_path),
        "env_values": ordered_values,
        "diff_summary": manual_diff_summary(ordered_values, current_env_path=current_env_path),
    }


def candidate_config_from_summary(summary: dict[str, Any], parameter_set_id: str) -> dict[str, Any]:
    configs = summary.get("configurations_by_id")
    if not isinstance(configs, dict):
        raise ValueError("Sweep summary does not contain configurations_by_id.")
    candidate = configs.get(parameter_set_id)
    if not isinstance(candidate, dict):
        raise ValueError(f"Unknown parameter_set_id: {parameter_set_id}")
    env_overrides = candidate.get("env_overrides")
    if not isinstance(env_overrides, dict):
        raise ValueError(f"Candidate {parameter_set_id} does not contain env_overrides.")
    return candidate


def manual_diff_summary(env_values: dict[str, Any], *, current_env_path: Path = Path(".env")) -> str:
    current = parse_env_file(current_env_path)
    lines = ["Manual diff-style summary for .env.candidate:"]
    for key, value in env_values.items():
        current_value = current.get(key, "<unset>")
        lines.append(f"- {key}={current_value}")
        lines.append(f"+ {key}={_env_value(value)}")
    return "\n".join(lines)


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    parsed: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        parsed[key.strip()] = value.strip()
    return parsed


def _ordered_env_values(env_values: dict[str, Any]) -> dict[str, Any]:
    preferred = [
        "PAPER_TRADING_ONLY",
        "SYMBOL",
        "TRADING_ENABLED",
        "AUTO_TRADE_ENABLED",
        "ALLOW_FALLBACK_TRADING",
        "SCALPING_MODE_ENABLED",
    ]
    ordered: dict[str, Any] = {}
    for key in preferred:
        if key in env_values:
            ordered[key] = env_values[key]
    for key in sorted(env_values):
        if key not in ordered:
            ordered[key] = env_values[key]
    return ordered


def _format_candidate_env(parameter_set_id: str, env_values: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/apply_candidate_config.py",
        f"# parameter_set_id={parameter_set_id}",
        "# Paper-forward candidate only. This file is not loaded automatically.",
        "# Backtests do not guarantee future profitability.",
    ]
    lines.extend(f"{key}={_env_value(value)}" for key, value in env_values.items())
    return "\n".join(lines) + "\n"


def _env_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


if __name__ == "__main__":
    main()
